### ISSUE TITLE
product_size_max defaults to 2000

### ISSUE THREAD

**Issue by ssb22** [SemiQuant/PrimerJinn#1]
Is a default `product_max_size` of 2000 really OK?  Primer Pooler's default `amp-max` is 220 because that seemed to be the consensus among the biologists I asked.  I'm not a biologist, I just talked with them long enough to figure out what to code, but wouldn't 2000 be a bit unstable?

(One thing I learned with Primer Pooler is we have to think about our defaults because "automation bias" is high.  An early version had the default temperature be 37 "because it's human DNA right?" and the default number of pools arbitrarily set to 3, I was expecting the biologists to change it but some of them took it seriously as in "computer says this, computer knows best".  Of course if I'd walked into their lab in person and said the same thing they'd throw me out, but if I get my software to say it that's different.  So I worked harder on trying to make sure all the defaults are sensible!)

**Comment by SemiQuant** [comment]
The default amplicon size max is 800, and while smaller (off target amplicons) amplicons will amplify more efficiently, the larger ones are harder to remove, and polymerase is quick so a 2kb can easily be amplified in the cycling for a 500bp. The default on ncbi primer-3 for looking at off target amplicons is 4kb. So I think 2knb is good, but happy to reconsider if you disagree. Agree completely with what you say about automation bias, the defaults I set are for this are the ones I use in the lab, and I think they should be pretty robust for targeted sequencing assay design.

**Comment by ssb22** [comment]
OK if that's what's working for you then best keep it :)
