### ISSUE TITLE
typo when calculating Tm 

### ISSUE THREAD

**Issue by leomrtns** [SemiQuant/PrimerJinn#3]
Hello! I haven't tried this software yet, but reading the code a bit, I wonder if perhaps the code line  https://github.com/SemiQuant/PrimerJinn/blob/3c18ff18e3be12179bfcc5f096b736cf1f5b0302/PrimerJinn/PCRinSilico.py#L59 should not be instead `if seq2 is '':` since `calcHeterodimer` is the function that needs `seq2`. 

Anyway this is just a random comment, it looks like a great piece of software!
sincerely,
Leo

**Comment by SemiQuant** [comment]
thanks, I fixed this.
